## Deploy nginx to all hosts
---
- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: yes

  collections:
    - nginxinc.nginx_core

  roles:
    - role: nginx_config
      vars:
        nginx_config_http_template_enable: true
        nginx_config_http_template:
          app:
            template_file: http/default.conf.j2
            conf_file_name: default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              main:
                listen:
                  listen_localhost:
                    port: 80
                server_name: localhost
                access_log:
                  - name: main
                    location: /var/log/nginx/access.log
                reverse_proxy:
                  locations:
                    main:
                      location: /
                      proxy_pass: http://upstr/
                      proxy_set_header:
                        header_host:
                          name: Host
                          value: $host
              server_one:
                listen:
                  listen_server_one:
                    port: 8008
                server_name: localhost
                access_log:
                  - name: main
                    location: /var/log/nginx/access.log
                web_server:
                  locations:
                    server_one:
                      location: /
                      html_file_location: /usr/share/nginx/html
                      html_file_name: server_one.html
                sub_filter:
                  once: false
                  sub_filters:
                    - "'server_hostname' '$hostname'"
                    - "'server_address' '$server_addr:$server_port'"
                    - "'server_url' '$request_uri'"
                    - "'remote_addr' '$remote_addr:$remote_port'"
                    - "'server_date' '$time_local'"
                    - "'client_browser' '$http_user_agent'"
                    - "'request_id' '$request_id'"
                    - "'nginx_version' '$nginx_version'"
                    - "'document_root' '$document_root'"
                    - "'proxied_for_ip' '$http_x_forwarded_for'"
              server_two:
                listen:
                  listen_server_two:
                    port: 8009
                server_name: localhost
                access_log:
                  - name: main
                    location: /var/log/nginx/access.log
                web_server:
                  locations:
                    server_two:
                      location: /
                      html_file_location: /usr/share/nginx/html
                      html_file_name: server_two.html
                sub_filter:
                  once: false
                  sub_filters:
                    - "'server_hostname' '$hostname'"
                    - "'server_address' '$server_addr:$server_port'"
                    - "'server_url' '$request_uri'"
                    - "'remote_addr' '$remote_addr:$remote_port'"
                    - "'server_date' '$time_local'"
                    - "'client_browser' '$http_user_agent'"
                    - "'request_id' '$request_id'"
                    - "'nginx_version' '$nginx_version'"
                    - "'document_root' '$document_root'"
                    - "'proxied_for_ip' '$http_x_forwarded_for'"
            upstreams:
              main:
                name: upstr
                lb_method: least_conn
                servers:
                  server_one:
                    address: 0.0.0.0
                    port: 8008
                  server_two:
                    address: 0.0.0.0
                    port: 8009

        nginx_config_html_demo_template_enable: true
        nginx_config_html_demo_template:
          server_one:
            template_file: www/index.html.j2
            html_file_location: /usr/share/nginx/html
            html_file_name: server_one.html
            web_server_name: Ansible NGINX collection -> Server One
          server_two:
            template_file: www/index.html.j2
            html_file_location: /usr/share/nginx/html
            html_file_name: server_two.html
            web_server_name: Ansible NGINX collection -> Server Two
